apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-repo-config
data:
  repos.yaml: |
      repos:
      - id: /.*/
        plan_requirements: [mergeable]
        apply_requirements: [approved]
        allowed_overrides: [workflow]
        pre_workflow_hooks:
          - run: echo "do nothing"
        post_workflow_hooks:
          - run: echo "did nothing"


