apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-repo-config
data:
  repos.yaml: |
    repos:
      - id: /.*/
        plan_requirements: [mergeable]
        apply_requirements: [approved]
        allowed_overrides:
          - workflow
        allow_custom_workflows: true
        pre_workflow_hooks:
          - run: echo "do nothing"


