apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-repo-config
data:
  repos.yaml: |
    repos:
    - id: /.*/
      apply_requirements: [approved, mergeable]
      allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
      allow_custom_workflows: true
      delete_source_branch_on_merge: true
      # pre_workflow_hooks:
      #   - run: echo "hello from pre workflow hook in default"


