apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  labels:
    app.kubernetes.io/name: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlantis
    spec:
      serviceAccountName: atlantis-sa
      containers:
        - name: atlantis
          # image: ghcr.io/runatlantis/atlantis:v0.28.3
          image: pranavs1995/atlantis-aws:5-71a2a39
          env:
          - name: ATLANTIS_REPO_ALLOWLIST
            value: github.com/pranavs1995/atlantis-demo
          ### GitHub Config ###
          - name: ATLANTIS_GH_USER
            value: pranavs1995
          - name: ATLANTIS_REPO_CONFIG
            value: "/etc/atlantis/repos.yaml"
          - name: ATLANTIS_GH_TOKEN
            valueFrom:
              secretKeyRef:
                name: atlantis-vcs
                key: token
          - name: ATLANTIS_GH_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: atlantis-vcs
                key: webhook-secret
          - name: ATLANTIS_PORT
            value: "4141"
          - name: ATLANTIS_LOG_LEVEL
            value: "debug"
          ports:
          - name: atlantis
            containerPort: 4141
          resources:
            requests:
              memory: 1024Mi
              cpu: 300m
            limits:
              memory: 1024Mi
              cpu: 300m
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
          volumeMounts:
          - name: atlantis-repo-config
            mountPath: /etc/atlantis
      volumes:
        - name: atlantis-repo-config
          configMap:
            name: atlantis-repo-config
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  type: ClusterIP
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
  selector:
    app.kubernetes.io/name: atlantis